### ISSUE TITLE
Readme says this project has documentation, but 90% of "documentation" is WIP

### ISSUE THREAD

**Issue by cvl** [nodegui/react-nodegui#177]
Readme says this project has documentation, but 90% of "documentation" is WIP

**Comment by master-atul** [comment]
Hey @cvl  

Yes, Thanks for a reminder related to docs.

Open source is hard and it requires tremendous effort and time from a lot of people involved.
I do agree though with you regarding docs. And I have decided to prioritize docs now. 
You should see an updated guide in the coming days. 
Also would you like to help out here as you discover nodegui/react-nodegui?

I will close this issue since there is nothing more actionable here.

In the meantime. You can get a quick intro here: https://www.youtube.com/watch?v=8jH5gaEEDv4

**Comment by master-atul** [comment]
I will start with updating nodegui guides, followed by react nodegui ones. But do not expect this to happen overnight. And I would like to get as much help as possible.

**Comment by cvl** [comment]
Sounds good, thanks for great work, Atul.
