### ISSUE TITLE
How to stream mp3 audio from http to react-nodegui?

### ISSUE THREAD

**Issue by abhigk** [nodegui/react-nodegui#195]
Hi
I am trying to make an audio stream application which can stream audio from internet without downloading it. However, I am not able to find any audio streaming on the nodejs server. There is several audio libraries for nodejs like '_play-sound_' however, it only plays an audio file that is on my computer. 
Please help me solve this problem. Cheers

**Comment by master-atul** [comment]
Hi @abhigk 
React NodeGui is a UI library for NodeJS. And hence, this issue is outside the scope of this project.

But a quick search on npm pointed me to this: https://github.com/audiojs
I think these questions are better suited for Stack overflow instead. Closing this issue since this is not actionable from the point of view of this project.
